# Kustomization for Microservices Base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bff
  - identity
  - lottery
  - order
  - wallet
  - winner
  - notification
  - audit
