# Secrets for LOCAL - JWT
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: cryptojackpot
type: Opaque
stringData:
  JWT_SECRET_KEY: "4ffe50319fbe565a10c6cb8b2300cf91ad85c31a73f1a96826f0907535fb868f"
  JWT_ISSUER: "CryptoJackpotIdentity"
  JWT_AUDIENCE: "CryptoJackpotApp"
