# Secrets for LOCAL - Redis (Data Protection Keys)
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: cryptojackpot
type: Opaque
stringData:
  REDIS_CONNECTION_STRING: "redis.cryptojackpot.svc.cluster.local:6379"

