# Secrets para desarrollo local - Kafka
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
  namespace: cryptojackpot
type: Opaque
stringData:
  KAFKA_BOOTSTRAP_SERVERS: "redpanda.cryptojackpot.svc.cluster.local:9092"
  KAFKA_SASL_USERNAME: ""
  KAFKA_SASL_PASSWORD: ""
  KAFKA_SASL_MECHANISM: ""
  KAFKA_SECURITY_PROTOCOL: "PLAINTEXT"
