# Secrets para desarrollo local - MongoDB
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: cryptojackpot
type: Opaque
stringData:
  MONGODB_ROOT_USERNAME: "admin"
  MONGODB_ROOT_PASSWORD: "mongodb_local_dev_2025"
  MONGODB_AUDIT_CONNECTION: "mongodb://admin:mongodb_local_dev_2025@mongodb.cryptojackpot.svc.cluster.local:27017/cryptojackpot_audit?authSource=admin"
  MONGODB_AUDIT_DATABASE: "cryptojackpot_audit"
